In [1]:
import numpy as np


- Creatin a simple numpy array

In [ ]:

one = np.zeros(10) #this will create an array with 10 zeros
one
#the zeros created will be floats


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- Create an numpy array from lists

In [6]:
list1 = [1,343,5,6,2,34,1,1]
num1 = np.array([list1]) #notice the list is placed in [] brackets
num1


array([[  1, 343,   5,   6,   2,  34,   1,   1]])

In [7]:
#from a 2dimensional array
list2 =  [['Keks','James','Homer'],[23,4,31]]
num2 = np.array([list2])
num2

array([[['Keks', 'James', 'Homer'],
        ['23', '4', '31']]], dtype='<U21')

- Creating random arrays

In [12]:

#####random.randint
np.random.seed(0)
nums = np.random.randint(90,size = 10) ##takes 3 args with one being the lowest integer in the array followed by the highest integer in the array and then the size of the array
nums

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])